language: julia
os:
  - linux
  - osx

julia:
  - 0.6.0

install:
  - julia -e 'Pkg.add("Conda");using Conda;Conda.add("matplotlib")'
  - julia -e 'Pkg.add("DataFrames")'
  - julia -e 'Pkg.add("NearestNeighbors")'
  - julia -e 'Pkg.add("DataStructures")'
  - julia -e 'Pkg.add("PyPlot")'

script:
  - julia ./test.jl
